server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
#      server-addr: nacos:8848
    gateway:
      routes:
        - id: user-service #路由标识 必须唯一
          uri: lb://userservice #路由的目标地址
          predicates: #路径断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否以/user开头

        - id: order-service #路由标识 必须唯一
          uri: lb://orderservice #路由的目标地址
          predicates: #路径断言，判断请求是否符合规则
            - Path=/order/** #路径断言，判断路径是否以/user开头
#      default-filters:
#        - AddRequestHeader=Truth, I LOVE U!

